### ISSUE TITLE
ruote-kit doesn't work with sinatra 1.1.0

### ISSUE THREAD

**Issue by rebo** [kennethkalmer/ruote-kit#7]
Just a heads up I get the following error when using ruote-kit and  sinatra 1.1.0 in my gem file

NoMethodError - undefined method `sub!' for nil:NilClass:
 /Users/rebo/.rvm/gems/ruby-1.9.2-p0@rails3/gems/activesupport-3.0.0/lib/active_support/whiny_nil.rb:48:in`method_missing'
 /Users/rebo/.rvm/gems/ruby-1.9.2-p0@rails3/gems/sinatra-respond_to-0.5.0/lib/sinatra/respond_to.rb:173:in `format'

I found this after doing a bundle update.

Not a major problem as I can specify gem 'sinatra', '1.0'.

**Comment by tosch** [comment]
This is a known issue which is tackled in 915611fd3249836292e9969fe9a8e76a1271f24d

See also cehoffman/sinatra-respond_to#3
